// These local keys help us keep browser-only preferences between visits.
export const STORAGE_KEY = 'mybills-transactions-v1'
export const MONTH_STORAGE_KEY = 'mybills-selected-month-v1'
export const RECURRING_MONTH_COUNT = 24

// These category suggestions mirror the way the bills are usually grouped.
export const CATEGORY_SUGGESTIONS = [
  'House',
  'Subscription',
  'Installments',
  'Transport',
  'Food',
  'Health',
  'Entertainment',
  'Income',
]

// These colors give each category card its own visual identity.
export const CATEGORY_COLORS = {
  House: '#74d66c',
  Subscription: '#ff8ad8',
  Installments: '#ffbe64',
  Transport: '#81d5ff',
  Food: '#ff8b7b',
  Health: '#8f95ff',
  Entertainment: '#c78dff',
  Income: '#6fcf97',
}

// This sample data keeps the dashboard populated for first-time users.
export const SEED_TRANSACTIONS = [
  {
    id: 'txn-1',
    title: 'Salary 1',
    type: 'income',
    amount: 1200,
    date: '2026-04-14',
    category: 'Income',
    notes: 'First pay cycle',
  },
  {
    id: 'txn-2',
    title: 'Salary 2',
    type: 'income',
    amount: 1200,
    date: '2026-04-28',
    category: 'Income',
    notes: 'Second pay cycle',
  },
  {
    id: 'txn-3',
    title: 'Rent',
    type: 'expense',
    amount: 620,
    date: '2026-04-09',
    category: 'House',
    notes: 'Main rent payment',
  },
  {
    id: 'txn-4',
    title: 'Electricity',
    type: 'expense',
    amount: 163.65,
    date: '2026-04-08',
    category: 'House',
    notes: 'Monthly utility bill',
  },
  {
    id: 'txn-5',
    title: 'Electricity',
    type: 'expense',
    amount: 175.09,
    date: '2026-04-27',
    category: 'House',
    notes: 'Catch-up payment',
  },
  {
    id: 'txn-6',
    title: 'Gas',
    type: 'expense',
    amount: 24.65,
    date: '2026-04-24',
    category: 'House',
    notes: 'Cooking gas top-up',
  },
  {
    id: 'txn-7',
    title: 'Internet',
    type: 'expense',
    amount: 89,
    date: '2026-04-18',
    category: 'House',
    notes: 'Home broadband',
  },
  {
    id: 'txn-8',
    title: 'Disney+',
    type: 'expense',
    amount: 15.99,
    date: '2026-04-05',
    category: 'Subscription',
    notes: 'Streaming',
  },
  {
    id: 'txn-9',
    title: 'Amazon',
    type: 'expense',
    amount: 9.99,
    date: '2026-04-01',
    category: 'Subscription',
    notes: 'Prime',
  },
  {
    id: 'txn-10',
    title: 'YouTube',
    type: 'expense',
    amount: 39.99,
    date: '2026-04-06',
    category: 'Subscription',
    notes: 'Family plan',
  },
  {
    id: 'txn-11',
    title: 'ChatGPT',
    type: 'expense',
    amount: 31.9,
    date: '2026-04-08',
    category: 'Subscription',
    notes: 'Work tools',
  },
  {
    id: 'txn-12',
    title: 'iCloud',
    type: 'expense',
    amount: 14.99,
    date: '2026-04-16',
    category: 'Subscription',
    notes: 'Storage',
  },
  {
    id: 'txn-13',
    title: 'iPhone',
    type: 'expense',
    amount: 15.99,
    date: '2026-04-29',
    category: 'Subscription',
    notes: 'Device storage upgrade',
  },
  {
    id: 'txn-14',
    title: 'Gym',
    type: 'expense',
    amount: 31.99,
    date: '2026-04-01',
    category: 'Installments',
    notes: 'Installment 1 of 4',
  },
  {
    id: 'txn-15',
    title: 'AP Chemist',
    type: 'expense',
    amount: 33.75,
    date: '2026-04-03',
    category: 'Installments',
    notes: 'Installment 1 of 4',
  },
  {
    id: 'txn-16',
    title: 'AP Amazon',
    type: 'expense',
    amount: 24.75,
    date: '2026-04-03',
    category: 'Installments',
    notes: 'Installment 1 of 4',
  },
  {
    id: 'txn-17',
    title: 'Salary 1',
    type: 'income',
    amount: 1260,
    date: '2026-05-14',
    category: 'Income',
    notes: 'Pay rise example',
  },
  {
    id: 'txn-18',
    title: 'Salary 2',
    type: 'income',
    amount: 1260,
    date: '2026-05-28',
    category: 'Income',
    notes: 'Pay rise example',
  },
  {
    id: 'txn-19',
    title: 'Rent',
    type: 'expense',
    amount: 620,
    date: '2026-05-09',
    category: 'House',
    notes: 'Main rent payment',
  },
  {
    id: 'txn-20',
    title: 'Internet',
    type: 'expense',
    amount: 89,
    date: '2026-05-18',
    category: 'House',
    notes: 'Home broadband',
  },
  {
    id: 'txn-21',
    title: 'ChatGPT',
    type: 'expense',
    amount: 31.9,
    date: '2026-05-08',
    category: 'Subscription',
    notes: 'Work tools',
  },
]
